name: Test action

on:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install required
        run: sudo apt-get install -y sqlcipher sqlite3-tools

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files: |
            *.db
